#!/usr/bin/env bash
# Install load balancer

echo "Updating and doing some minor checks..."

function install() {
    if ! command -v "$1" &> /dev/null; then
        echo "Installing: $1"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq || {
                echo "Error: Failed to install $1"
                exit 1
            }
        echo
    else
        echo "${1} is already installed."
    fi
}

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
defaults
    mode http
    timeout connect 5s
    timeout client 10s
    timeout server 15s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 257591-web-01 52.86.186.195:80 check
    server 257591-web-02 54.144.152.117:80 check
EOF

# Enable HAProxy to be managed via an init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy >/dev/null

echo "configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
        sudo service haproxy start
else
        sudo service haproxy restart
fi

# Restart HAProxy service
sudo systemctl restart haproxy
